# Generated by Django 3.2 on 2021-05-06 11:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('fps', 'First-Person Shooter'), ('rp', 'Role-Play'), ('sg', 'Strategy Game'), ('moba', 'Mulitplayer Online Battle Arena'), ('ftp', 'Free to Play')], max_length=4)),
                ('fsk', models.CharField(choices=[('0', 'FSK 0'), ('6', 'FSK 6'), ('12', 'FSK 12'), ('16', 'FSK 16'), ('18', 'FSK 18')], max_length=2)),
                ('creator', models.CharField(max_length=50)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['title', '-type'],
            },
        ),
    ]
